=== PedroRangelP/ITC11/6th semester/Advanced Database Systems/XML Databases/company.dtd
<!ELEMENT COMPANY (ASG*)>
<!ELEMENT ASG (EMP,PROJECT,RESP,DUR)>
<!ELEMENT EMP (Ename, Title, Sal)>
<!ATTLIST EMP Eno CDATA #REQUIRED>
<!ELEMENT Ename (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Sal (#PCDATA)>
<!ELEMENT PROJECT (Pname, Budget, Loc)>
<!ATTLIST PROJECT Pno ID #REQUIRED>
<!ELEMENT Pname (#PCDATA)>
<!ELEMENT Budget (#PCDATA)>
<!ELEMENT Loc (#PCDATA)>
<!ELEMENT RESP (#PCDATA)>
<!ELEMENT DUR (#PCDATA)>

=== PedroRangelP/ITC11/6th semester/Advanced Database Systems/XML Databases/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COMPANY SYSTEM "company.dtd">
<COMPANY>
	<ASG>
		<EMP Eno='E01'>
			<Ename>John Smith</Ename>
			<Title>Sys. Admin</Title>
			<Sal>10000</Sal>
		</EMP>
		<PROJECT Pno='P01'>
			<Pname>Project X</Pname>
			<Budget>500000</Budget>
			<Loc>San Francisco</Loc>
		</PROJECT>
		<RESP>Manager</RESP>
		<DUR>12</DUR>
	</ASG>
	
	<ASG>
		<EMP Eno='E01'>
			<Ename>John Smith</Ename>
			<Title>Sys. Admin</Title>
			<Sal>10000</Sal>
		</EMP>
		<PROJECT Pno='P02'>
			<Pname>Project Y</Pname>
			<Budget>800000</Budget>
			<Loc>San Francisco</Loc>
		</PROJECT>
		<RESP>Worker</RESP>
		<DUR>6</DUR>
	</ASG>
	
</COMPANY>
