=== PedroRangelP/ITC11/6th semester/Advanced Database Systems/XML Databases/activity_1/pubs.dtd
<!ELEMENT pubs (pub*, costumer*)>
<!ELEMENT pub (pname, area, beer*)>
<!ATTLIST pub pid ID #REQUIRED>
<!ELEMENT pname (#PCDATA)>
<!ELEMENT area (#PCDATA)>
<!ELEMENT beer (bname, color, country)>
<!ATTLIST beer bid ID #REQUIRED price CDATA #REQUIRED>
<!ELEMENT bname (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT costumer (cname, gender, age)>
<!ATTLIST costumer cid ID #REQUIRED frequents IDREFS #IMPLIED likes IDREFS #IMPLIED>
<!ELEMENT cname (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== PedroRangelP/ITC11/6th semester/Advanced Database Systems/XML Databases/activity_1/pubs.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pubs SYSTEM "pubs.dtd">
<pubs>
  <pub pid="P1">
    <pname>Celtic's</pname>
    <area>Polanco</area>
    <beer bid="B1-P1" price="80">
      <bname>Becks</bname>
      <color>Blond</color>
      <country>Germany</country>
    </beer>
    <beer bid="B2-P1" price="60">
      <bname>Guinness</bname>
      <color>Dark</color>
      <country>Ireland</country>
    </beer>
    <beer bid="B3-P1" price="50">
      <bname>Heineken</bname>
      <color>Blond</color>
      <country>Netherlands</country>
    </beer>
  </pub>
  <pub pid="P2">
    <pname>King's</pname>
    <area>Satélite</area>
    <beer bid="B2-P2" price="100">
      <bname>Guinness</bname>
      <color>Dark</color>
      <country>Ireland</country>
    </beer>
  </pub>
  <pub pid="P3">
    <pname>Eire</pname>
    <area>Condesa</area>
    <beer bid="B3-P3" price="50">
      <bname>Heineken</bname>
      <color>Blond</color>
      <country>Netherlands</country>
    </beer>
  </pub>
  <pub pid="P4">
    <pname>St. Patrick's</pname>
    <area>Condesa</area>
    <beer bid="B3-P4" price="45">
      <bname>Heineken</bname>
      <color>Blond</color>
      <country>Netherlands</country>
    </beer>
    <beer bid="B4-P4" price="40">
      <bname>Saporo</bname>
      <color>Blond</color>
      <country>Japan</country>
    </beer>
  </pub>
  <pub pid="P5">
    <pname>Nada</pname>
    <area>Atizapán</area>
    <beer bid="B5-P5" price="20">
      <bname>Bohemia</bname>
      <color>Blond</color>
      <country>México</country>
    </beer>
  </pub>
  <costumer cid="C1" frequents="P1 P2" likes="B1-P1 B2-P2">
    <cname>John</cname>
    <gender>Male</gender>
    <age>24</age>
  </costumer>
  <costumer cid="C2" frequents="P2" likes="B2-P2">
    <cname>Mary</cname>
    <gender>Female</gender>
    <age>28</age>
  </costumer>
  <costumer cid="C3" frequents="P3 P5" likes="B3-P3">
    <cname>Alice</cname>
    <gender>Female</gender>
    <age>36</age>
  </costumer>
  <costumer cid="C4" frequents="P4" likes="B2-P1 B4-P4">
    <cname>Bob</cname>
    <gender>Male</gender>
    <age>32</age>
  </costumer>
  <costumer cid="C5" frequents="P5 P1" likes="B5-P5">
    <cname>Pete</cname>
    <gender>Male</gender>
    <age>39</age>
  </costumer>
</pubs>
